### ISSUE TITLE
portal alignment north-south vs east-west

### ISSUE THREAD

**Issue by meoso** [MassiveCraft/CreativeGates#100]
it _seems_ with Spigot 1.8, portal plugins have an issue creating correctly aligned portals.  North-South portals looks correct, but for East-West portals, the portal block (90) is 90 degrees out.
reference: http://www.spigotmc.org/threads/portal-90-block-orientation-n-s-vs-e-w.43267/

It does not seem to be an issue when creative standard portals using "flint and steel".

Thank you.

**Comment by oloflarsson** [comment]
Is this a client side rendering bug?
What happens if you make a creative gate out of obsidian?

**Comment by meoso** [comment]
i wouldn't know if it a client-side render bug. 

obsidian-only creativegate still does this.

```
  "blocksrequired": {
    "OBSIDIAN" : 10
  },
```

**Comment by Chusca** [comment]
I have the same issue... any solution? 
Thx

**Comment by meoso** [comment]
Thanks to Enzo93 : http://www.spigotmc.org/threads/portal-90-block-orientation-n-s-vs-e-w.43267/#post-608445
Temporary solution WordEdit your portal and `//replace 90 90:2`

**Comment by oloflarsson** [comment]
This bug has now been fixed
https://github.com/MassiveCraft/CreativeGates/commit/3b28faf0e30e45e962efe658ac5a4af4698a7a15

**Comment by meoso** [comment]
Thank you!  is there a Jenkins build somewhere? i can't seem to get this going myself with eclipse.
