### ISSUE TITLE
Config file not working

### ISSUE THREAD

**Issue by cclloyd** [MassiveCraft/CreativeGates#101]
When editing the confit file, it is deleting lines where I change the item/block required for somethign.

When I change the block required for a portal, it deletes the line.  When I change the item used to inspect or toggle mode, etc. it deletes it.

Sometimes it will readd the line with the default option, but it's only sometimes.

I'm editing /mconf/creativegates_uconf@default/instance.json

**Comment by oloflarsson** [comment]
You are probably misspelling the material.
