### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by xPedroPT** [MassiveCraft/CreativeGates#103]
When i enter the portal i dont go anywhere (srry my english) Pls Help

**Comment by oloflarsson** [comment]
You message is too short and contains too little information to be a proper bug report. You need to specify much more information. What server version are you using? What plugin versions are you using? What messages appear in console? What steps should be taken in order to make this bug appear?

**Comment by xPedroPT** [comment]
Im using the last version. Im in version 1.7.2. And in the console dont apeer nothing...
