### ISSUE TITLE
Add more portal materials

### ISSUE THREAD

**Issue by Bodyash** [MassiveCraft/CreativeGates#104]
can u add SugarCane type of gates? Or Web... or any other block.
Like in AncientGates plugin

**Comment by Bodyash** [comment]
https://www.youtube.com/watch?feature=player_embedded&v=AeAebY6rBSU

Like in AncientGates

**Comment by Walkman100** [comment]
Ok so this is for the actual teleport blocks, in AncientGates you can use Sugarcane and a few other things instead of the water or portal blocks

**Comment by morfie78** [comment]
I like this idea, too.  We run into issues with the water from time-to-time.

**Comment by oloflarsson** [comment]
I do not think we will add this feature to CreativeGates. When we get the time we will recode CreativeGates and revive the Ancient Gates functionality.

So for the future we will make a plugin covering this feature. CreativeGates will remain very simple.
