### ISSUE TITLE
The portal going side way.

### ISSUE THREAD

**Issue by luong8000** [MassiveCraft/CreativeGates#109]
The portal going side ways when I create one with a watch. It make it side ways. Not the portal frame the something in the frame.

**Comment by meoso** [comment]
This is a duplicate of issue [#100](https://github.com/MassiveCraft/CreativeGates/issues/100) which has been fixed in source code; however, the build has not been uploaded to spigot/bukkit.

Please read the issue thread for a manual fix (via worldedit).

**Comment by oloflarsson** [comment]
Fixed.
