### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by galaipa** [MassiveCraft/CreativeGates#111]
Sometimes this error spams the console and the players lose their inventory ( Using MultiInv plugin)
-I use spigot 1.8.8
- Latest version of MassiveCore/CreativeGates

Error: http://pastebin.com/vaLtt06L

**Comment by ulumulu1510** [comment]
Please state exactly which versions of MassiveCore and Factions you are using.

Your error was mildly helpfull, but I need more information about the circumstances aswell. Please provide these information an then I can help you @galaipa.

**Comment by galaipa** [comment]
Hi, thanks for your reply.
Using MassiveCore 2.8.0
CreativeGates  2.8.0

It happens sometimes when a player uses a portal

**Comment by ulumulu1510** [comment]
Please define "sometimes". My initial guess was mixed version numbers in MassiveCore and CreativeGates, but it wasn't that.

We are using these versions ourselfs and never encountered the issues so far, so please state exactly under which cicircumstances it happens:
-online/offline mode of the players
-bungeecord setrup or not 
- same world or not (both portals)
.... and as much as you can give us.

Please also do a clean install on a test server of only Spigot, MassiveCore and CreativeGates and try whether the issues persist. If not, try to add one plugin after another and report the problem to the author of the plugin which is causing this.

If creativegates is the issue, please come back with as much information as you can Provide.

**Comment by ulumulu1510** [comment]
It seems to have resolved itself.
