### ISSUE TITLE
Random waterfalls?

### ISSUE THREAD

**Issue by Fiordhraoi** [MassiveCraft/CreativeGates#114]
Hello,

I have the plugin working properly and my gates work great.  However, after installing this, I noticed odd waterfalls appearing, usually around chunk boundaries, but not ALL chunk boundaries.  And they're more dense in some areas than others (this is the densest I saw).

![2015-11-03_11 42 49](https://cloud.githubusercontent.com/assets/8886777/10915555/58711ccc-8225-11e5-88e2-f5413baf5f3d.png)

This is a brand new Bukkit server I just started, and the only plugins installed are Creative Gates and WorldEdit (and Massive Core, of course).

The only configuration option I changed was to enable water instead of Nether for the gate effect.

Do you think this could be related at all?  The only reason I suspect it is because the water effect on the portal is the only water-related modified thing on this server.  Any assistance in tracking down the issue would be great.  Thank you!

**Comment by ulumulu1510** [comment]
Well that is an interresting issue! Thank you for reporting it @Fiordhraoi.

Please state what versions you use of:
* Bukkit/Spigot
* MassiveCore
* CreativeGates

Do you have any error logs you potentially could provide? Any regularities? Did you even create any gates so far?

**Comment by Fiordhraoi** [comment]
I'm using Bukkit 1.8.8, and both MassiveCore and CreativeGates are at 2.8.2.

I'm not seeing any errors in the logs at all, but I'd be happy to send them over if you like.  I have created 6 gates, two of which I destroyed after testing.

Oh, this server WAS on vanilla for a few days before I loaded it into Bukkit, but I didn't see the errors until I then shut it down again and loaded Massive / Creative.

**Comment by ulumulu1510** [comment]
This is indeed an issue I have never encountered before and is rather strange to me, but lets see whether we can gather some more information here:
* Does it happen in all worlds, (above, nether, any other costum worlds you might have)?
* Could you pastebin your config from CreativeGates and link it here?
* Are the gates running properly? Are they working as you excpect them to?
* Do you use Bukkit 1.8.8 or Spigot 1.8.8? Note that there is a difference between the two and if you can I'd advise running the spigot jar instead of the craftBukkit one.

**Comment by Fiordhraoi** [comment]
I'm only running the default worlds.  I have not seen this behavior in the Nether.

Here's the pastebin: http://pastebin.com/f4kCJe03

Gates are running perfectly, with no issues.

I am running Bukkit 1.8.8, not Spigot.  I admit I'm not familiar with the differences - Should I just be able to get the spigot 1.8.8 JAR into my server directory and run it in place of the craftbukkit one?  (Also, due to the current legal issues, I'm not sure where to find Spigot).

**Comment by ulumulu1510** [comment]
If you used the Buildtools from the spigot website, the spigot.yml is also compiled  automatically to the same directory where the bukkit one is comipled to. 
If you have the buildtools from somewhere else, these steps above will probably not work ^^.

Running the spigot.jar instead of the craftbukkit.jar will work without issues. Just make sure you change the run batch file (or the way you start your server ) to address spigot.jar instead.

I will look into the config in a few minutes and report back.

**Comment by Fiordhraoi** [comment]
Sounds good, I'll see if I can get the buildtools from Spigot and go from there.

**Comment by ulumulu1510** [comment]
The json is valid, so no issues on that side.
Do you have any idea when these waterfalls are being created? Were they (eventually) there before? If new ones are created, under what circumstances?

**Comment by ulumulu1510** [comment]
note that you should be fine runing craftbukkit for this plugin, it is just a personal recomendation if you are going to use other plugins of our MassivePlugin collection or from spigot.

**Comment by Fiordhraoi** [comment]
I just installed Massive Core and Creative Gates last night, at about 10pm EST.  When I went to bed a couple hours later, I hadn't noticed the waterfalls at all.  This morning, one of my friends said he noticed them at about 9am EST when he logged in.

It's difficult to say if new ones are still being created.  At the very least, I'm not seeing more appearing in the area near the spawn (only about 4 appeared near there).  I'll see if I can scoop those up in buckets and whether or not they reappear.

If it would help at all, I'm happy to give you access and op, it's just a new server I threw up for my friends and I to play on, and it's only 5 days old or so, so even if it crashed and burned right now, we wouldn't lose any incredible amount of work.

**Comment by ulumulu1510** [comment]
If you can give me the server adress I'll gladly hop on and have a look ingame and see what is going on ingame atleast. My username is the same as on github.

**Comment by Fiordhraoi** [comment]
The server is at draoi.ddns.net .  Once you connect, I'll edit this so it's not publicly available anymore, so I don't have to build a whitelist.  :)

**Comment by Fiordhraoi** [comment]
Also, it's definitely still happening - one just appeared in the middle of our first base camp, that wasn't there last time I was logged in.

**Comment by Fiordhraoi** [comment]
For anyone else reading this thread, wasn't able to isolate a cause or even determine for certain that it was CreativeGates/MassiveCore doing it, but if any new information pops up I'll repost here for posterity.

**Comment by ulumulu1510** [comment]
As discussed on the server, if further evidence/information arrises, pelase report back and I'll re-open the issue.
