### ISSUE TITLE
Creative Gates Error

### ISSUE THREAD

**Issue by AndreNicolas** [MassiveCraft/CreativeGates#119]
19.03 18:11:38 [Server] INFO ... 29 more
19.03 18:11:38 [Server] INFO at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_72]
19.03 18:11:38 [Server] INFO at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_72]
19.03 18:11:38 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[CraftBukkit18.jar:git-Bukkit-33d5de3]
19.03 18:11:38 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77) ~[CraftBukkit18.jar:git-Bukkit-33d5de3]
19.03 18:11:38 [Server] INFO at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.7.0_72]
19.03 18:11:38 [Server] INFO at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_72]
19.03 18:11:38 [Server] INFO at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_72]
19.03 18:11:38 [Server] INFO at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_72]
19.03 18:11:38 [Server] INFO Caused by: java.lang.ClassNotFoundException: com.massivecraft.massivecore.predicate.Predicate
19.03 18:11:38 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.7.0_72]
19.03 18:11:38 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:517) [CraftBukkit18.jar:git-Bukkit-33d5de3]
19.03 18:11:38 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:609) [CraftBukkit18.jar:git-Bukkit-33d5de3]
19.03 18:11:38 [Server] INFO at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284) [CraftBukkit18.jar:git-Bukkit-33d5de3]
19.03 18:11:38 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:656) [CraftBukkit18.jar:git-Bukkit-33d5de3]
19.03 18:11:38 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.7.0_72]
19.03 18:11:38 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.7.0_72]
19.03 18:11:38 [Server] INFO at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [CraftBukkit18.jar:git-Bukkit-33d5de3]
19.03 18:11:38 [Server] INFO at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(SourceFile:9) [CraftBukkit18.jar:git-Bukkit-33d5de3]
19.03 18:11:38 [Server] INFO at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(SourceFile:37) [CraftBukkit18.jar:git-Bukkit-33d5de3]
19.03 18:11:38 [Server] INFO at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:919) [CraftBukkit18.jar:git-Bukkit-33d5de3]
19.03 18:11:38 [Server] INFO at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1058) [CraftBukkit18.jar:git-Bukkit-33d5de3]
19.03 18:11:38 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:625) [CraftBukkit18.jar:git-Bukkit-33d5de3]
19.03 18:11:38 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) [CraftBukkit18.jar:git-Bukkit-33d5de3]
19.03 18:11:38 [Server] INFO at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [CraftBukkit18.jar:git-Bukkit-33d5de3]
19.03 18:11:38 [Server] INFO at org.bukkit.Bukkit.reload(Bukkit.java:543) [CraftBukkit18.jar:git-Bukkit-33d5de3]
19.03 18:11:38 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.CraftServer.reload(CraftServer.java:725) [CraftBukkit18.jar:git-Bukkit-33d5de3]
19.03 18:11:38 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:313) [CraftBukkit18.jar:git-Bukkit-33d5de3]
19.03 18:11:38 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:341) [CraftBukkit18.jar:git-Bukkit-33d5de3]
19.03 18:11:38 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [CraftBukkit18.jar:git-Bukkit-33d5de3]
19.03 18:11:38 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:327) [CraftBukkit18.jar:git-Bukkit-33d5de3]
19.03 18:11:38 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[CraftBukkit18.jar:git-Bukkit-33d5de3]
19.03 18:11:38 [Server] INFO at com.massivecraft.creativegates.CreativeGates.onEnable(CreativeGates.java:83) ~[?:?]
19.03 18:11:38 [Server] INFO at com.massivecraft.massivecore.store.Colls.init(Colls.java:26) ~[?:?]
19.03 18:11:38 [Server] INFO at com.massivecraft.massivecore.store.Colls.getColls(Colls.java:36) ~[?:?]
19.03 18:11:38 [Server] INFO at com.massivecraft.massivecore.store.Colls.getForUniverse(Colls.java:71) ~[?:?]
19.03 18:11:38 [Server] INFO at com.massivecraft.massivecore.store.Colls.getForCollname(Colls.java:79) ~[?:?]
19.03 18:11:38 [Server] INFO at com.massivecraft.creativegates.entity.UGateColls.createColl(UGateColls.java:1) ~[?:?]
19.03 18:11:38 [Server] INFO at com.massivecraft.creativegates.entity.UGateColls.createColl(UGateColls.java:23) ~[?:?]
19.03 18:11:38 [Server] INFO java.lang.NoClassDefFoundError: com/massivecraft/massivecore/predicate/Predicate
19.03 18:11:38 [Server] ERROR Error occurred while enabling CreativeGates v2.8.6 (Is it up to date?)

**Comment by ulumulu1510** [comment]
MassivePlugins release in batches. It is important that all MassivePlugins share the same version number to function properly. Make sure to delete the current MassiveCore and CreativeGates and then put both plugins from the same plugin batch (preferably gotten from spigot
