### ISSUE TITLE
Gates won't activate

### ISSUE THREAD

**Issue by cnsenior** [MassiveCraft/CreativeGates#120]
When I hit the clock inside the frame, nothing happens. Outside the frame, i get error message "there is no frame for the gate or it's too big".

Bukkit 1.9
Minecraft 1.9
Massive Core 2.8.7
Creative Gates 2.8.7

Water and i changed it to gold_block from emerald_block.

Thanks if anyone has any advice!

**Comment by ulumulu1510** [comment]
Can you provide us with scrennshots of the gate you want to activate?

And please check your logs for errors and pastebin those for us.

Thanks.

**Comment by oloflarsson** [comment]
You probably had a hole in you gate frame. Closing this issue since there has been no feedback in 3 weeks.
