### ISSUE TITLE
Portal with STONEBRICK and variant

### ISSUE THREAD

**Issue by EtorS** [MassiveCraft/CreativeGates#123]
Im using 2.8.7Beta on Spigot 1.9.0, when i try to make a portal with STONEBRICK or some variant (changed in the cfg "blocksrequired") the console report this error:

`03.04 20:38:25 [Multicraft] Skipped 2 lines due to rate limit (30/s)
03.04 20:38:01 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0]
03.04 20:38:01 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0]
03.04 20:38:01 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0]
03.04 20:38:01 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0]
03.04 20:38:01 [Server] INFO at com.massivecraft.creativegates.EngineMain.tools(EngineMain.java:420) ~[?:?]
03.04 20:38:01 [Server] INFO at com.massivecraft.creativegates.MaterialCountUtil.desc(MaterialCountUtil.java:52) ~[?:?]
03.04 20:38:01 [Server] INFO at com.massivecraft.massivecore.util.Txt.getMaterialName(Txt.java:427) ~[?:?]
03.04 20:38:01 [Server] INFO at com.massivecraft.massivecore.util.Txt.getNicedEnum(Txt.java:422) ~[?:?]
03.04 20:38:01 [Server] INFO Caused by: java.lang.NullPointerException
03.04 20:38:01 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.7.0]
03.04 20:38:01 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.jar:git-Spigot-129f87a-6067e54]
03.04 20:38:01 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.jar:git-Spigot-129f87a-6067e54]
03.04 20:38:01 [Server] INFO at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.jar:git-Spigot-129f87a-6067e54]
03.04 20:38:01 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-1.9.jar:git-Spigot-129f87a-6067e54]
03.04 20:38:01 [Server] INFO at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9.jar:git-Spigot-129f87a-6067e54]
03.04 20:38:01 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.7.0]
03.04 20:38:01 [Server] INFO at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source) [?:1.7.0]
03.04 20:38:01 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.7.0]
03.04 20:38:01 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.jar:git-Spigot-129f87a-6067e54]
03.04 20:38:01 [Server] INFO at net.minecraft.server.v1_9_R1.PacketPlayInUseItem.a(SourceFile:11) [spigot-1.9.jar:git-Spigot-129f87a-6067e54]
03.04 20:38:01 [Server] INFO at net.minecraft.server.v1_9_R1.PacketPlayInUseItem.a(SourceFile:55) [spigot-1.9.jar:git-Spigot-129f87a-6067e54]
03.04 20:38:01 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:888) [spigot-1.9.jar:git-Spigot-129f87a-6067e54]
03.04 20:38:01 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerInteractManager.a(PlayerInteractManager.java:482) [spigot-1.9.jar:git-Spigot-129f87a-6067e54]
03.04 20:38:01 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231) [spigot-1.9.jar:git-Spigot-129f87a-6067e54]
03.04 20:38:01 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.jar:git-Spigot-129f87a-6067e54]
03.04 20:38:01 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.jar:git-Spigot-129f87a-6067e54]
03.04 20:38:01 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.jar:git-Spigot-129f87a-6067e54]
03.04 20:38:01 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.jar:git-Spigot-129f87a-6067e54]
03.04 20:38:01 [Server] INFO org.bukkit.event.EventException
03.04 20:38:01 [Server] ERROR Could not pass event PlayerInteractEvent to CreativeGates v2.8.7Beta`

and of course the gate is not created.

**Comment by magnusulf** [comment]
Use pastebin or another legible thing. This is difficult to read.

**Comment by Walkman100** [comment]
or wrap it in proper triple-backticks:

    ```
    <log>
    ```
(Documentation [here](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown))

**Comment by oloflarsson** [comment]
Closing since there were no answer. Feel free to reopen the ticket with fresh information if this is still an issue for you.
