### ISSUE TITLE
FurnitureLib plugin

### ISSUE THREAD

**Issue by mat41997** [MassiveCraft/CreativeGates#125]
to normal teleport with other teleport plugin
![1](https://cloud.githubusercontent.com/assets/5884000/15711968/9e25ecac-2810-11e6-977b-c6f1578f6da5.png)

teleport with CreativeGates portal
![2](https://cloud.githubusercontent.com/assets/5884000/15711975/a63749a4-2810-11e6-8659-96a68f2dd6bc.png)

link to FurnitureLib plugin
https://www.spigotmc.org/resources/furniturelibary-protectionlib.9368/

timings
https://timings.aikar.co/v2/?id=6a6501b9679e433898158e8c280eb4d5

**Comment by MarkehMe** [comment]
Please explain your issue. Otherwise, we have no idea what you are talking about 😞

**Comment by Walkman100** [comment]
> during teleportation, chairs vanish

that seems pretty explanatory to me...

**Comment by MarkehMe** [comment]
Thanks for editing your message.. I am taking my time here to help you with your issue, so work with me here. This issue doesn't happen in vanilla minecraft. So, I don't see why this would be a CreativeGates issue. 

Have you tried bringing the issue up with FurnitureLib as well?

What other portal plugins have you tried?
