### ISSUE TITLE
Permissions not working

### ISSUE THREAD

**Issue by julesle123456789** [MassiveCraft/CreativeGates#127]
I gave my admins creativegates.* creativegates.create creativegates.use but they still can't make portals, only ops can. How do I fix this?

**Comment by julesle123456789** [comment]
they can't even use it

**Comment by MarkehMe** [comment]
There must be something wrong with your permissions plugin. Do you have Vault?

**Comment by julesle123456789** [comment]
Yes I have vault, all of the other permissions work I user Pex

**Comment by MarkehMe** [comment]
Happy to help you out! Mind answering some Q's so I have a better understanding of your issue?

* MassiveCore version
* CreativeGates version
* Bukkit/Spigot version
* Are you sure its a permission issue?
* What message are you getting?
* Does the plugin load in the console? 
* Are there any stack traces or errors from the plugin in the console?

**Comment by julesle123456789** [comment]
MassiveCore: 2.8.19
CreativeGates: 2.8.19
Spigot : 1.10
Yes, it says: You do not have permission to create a gate
Yes I think
nope

**Comment by morfie78** [comment]
julesle, try using the debug feature of pex to see what permission node it is failing on.
1. Go to https://github.com/PEXPlugins/PermissionsEx/wiki/Commands
2. Scroll to "Utility commands" and look at 'pex toggle debug' and 'pex user <user> toggle debug.

A note: on an active server, pex toggle debug puts a LOT of output into your console.  Best to use it when there aren't many people on, and only have it on for a few seconds.   If pex user <user> toggle debug works for you, that would be better, as it is user-specific, and doesn't do as much output.

What I do:

1. Enable pex debug
2. Quickly replicate the action that is failing.
3. Quickly turn off pex debug.
4. Review the console/log files to see what node got in the way.

Hope this helps.

**Comment by julesle123456789** [comment]
Nothing apeared

**Comment by morfie78** [comment]
Did you try the pex toggle debug or pex user toggle debug? Sometimes the user one doesn't work. Also check the log file itself just in case, after pex toggle debug.

**Comment by julesle123456789** [comment]
I am very sorry to have wasted your time I derped gianormisly I forgot the "s" in creativegates

**Comment by morfie78** [comment]
It's all good. It happens to all of us!

**Comment by MarkehMe** [comment]
😆  Ooops! Happy to hear you've sorted the issue though.
