### ISSUE TITLE
Could not calculate the location

### ISSUE THREAD

**Issue by SBlack08** [MassiveCraft/CreativeGates#128]
Hi, i have unfortunately the problem that after some time the portals no longer find.
I have already tried to fix this in which I have placed on the portals a chunkloader ... unfortunately without success. Is there anything I've overlooked?

My System:
KCauldron 1.7.10 + Infinity Evolved 2.6.0

Portal 1 Overworld
Portal 2 example DIM30

**Comment by ulumulu1510** [comment]
Please state your versions of:
* CreativeGates 
* MassiveCore

Describe detailed:
* What you did
* What you expected to happen
* What actually happened.

Also, add screenshots/pastebins of any errors you have in console.
