### ISSUE TITLE
It didn't load!

### ISSUE THREAD

**Issue by RGamesGitHub** [MassiveCraft/CreativeGates#129]
I did all the steps and tryed it.
It didn't work.
The java file didnt make a folder. Pls help!
(My server made with server.pro (website) that is bukkit 1.10.2)

**Comment by ulumulu1510** [comment]
Please state your versions of:
* CrestiveGates
* MassiveCore
* Spigot

Describe detailed:
* What you did
* What you expected to happen
* What actually happened.

Also, add screenshots/pastebins of any errors you have in console.

Most of the time people forget massivecore, so please make sure you have that one.

**Comment by RGamesGitHub** [comment]
It was the 1.10.2 bukkit one.
I used it in server.pro.
I tryed it but the plugin didn't load at all. Its help did not appear in
the /help menu,

**Comment by ulumulu1510** [comment]
Please state your versions of:

- CreativeGates
- MassiveCore

I still can't help you if you don't provide me with these. Also have you made absolutely sure you also have MassiveCore in your plugins folder?

**Comment by RGamesGitHub** [comment]
???
I JUST WANT 1.10.2 PORTALS FOR MY SERVERRRRRRR
:(

**Comment by RGamesGitHub** [comment]
Oh.

**Comment by RGamesGitHub** [comment]
I am a dumbass.
I need the MassiveCore.
(faceslap)

**Comment by ulumulu1510** [comment]
Yes. If you would have read the page a little, MassiveCore is needed to run Creativegates. I assume i can close this now.
