### ISSUE TITLE
Error after a server restart with no changes to the server

### ISSUE THREAD

**Issue by gameitall** [MassiveCraft/CreativeGates#77]
i have also tried updating both mcore and creative gates, The server will start and allow players in if i remove Creative gates, but i need them

08.02 21:14:17 [Server] INFO at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:424) [craftbukkit_dev.jar:git-Bukkit-1.7.2-R0.2-40-g6e27629-b3011jnks]
08.02 21:14:17 [Server] INFO at net.minecraft.server.v1_7_R1.DedicatedServer.init(DedicatedServer.java:175) ~[craftbukkit_dev.jar:git-Bukkit-1.7.2-R0.2-40-g6e27629-b3011jnks]
08.02 21:14:17 [Server] INFO at net.minecraft.server.v1_7_R1.MinecraftServer.a(MinecraftServer.java:275) ~[craftbukkit_dev.jar:git-Bukkit-1.7.2-R0.2-40-g6e27629-b3011jnks]
08.02 21:14:17 [Server] INFO at net.minecraft.server.v1_7_R1.MinecraftServer.g(MinecraftServer.java:319) ~[craftbukkit_dev.jar:git-Bukkit-1.7.2-R0.2-40-g6e27629-b3011jnks]
08.02 21:14:17 [Server] INFO at net.minecraft.server.v1_7_R1.MinecraftServer.m(MinecraftServer.java:342) ~[craftbukkit_dev.jar:git-Bukkit-1.7.2-R0.2-40-g6e27629-b3011jnks]
08.02 21:14:17 [Server] INFO at org.bukkit.craftbukkit.v1_7_R1.CraftServer.enablePlugins(CraftServer.java:385) ~[craftbukkit_dev.jar:git-Bukkit-1.7.2-R0.2-40-g6e27629-b3011jnks]
08.02 21:14:17 [Server] INFO at org.bukkit.craftbukkit.v1_7_R1.help.SimpleHelpMap.initializeCommands(SimpleHelpMap.java:138) ~[craftbukkit_dev.jar:git-Bukkit-1.7.2-R0.2-40-g6e27629-b3011jnks]
08.02 21:14:17 [Server] INFO at org.bukkit.craftbukkit.v1_7_R1.help.CommandAliasHelpTopic.<init>(CommandAliasHelpTopic.java:18) ~[craftbukkit_dev.jar:git-Bukkit-1.7.2-R0.2-40-g6e27629-b3011jnks]
08.02 21:14:17 [Server] INFO at org.apache.commons.lang.Validate.isTrue(Validate.java:157) ~[craftbukkit_dev.jar:git-Bukkit-1.7.2-R0.2-40-g6e27629-b3011jnks]
08.02 21:14:17 [Server] INFO java.lang.IllegalArgumentException: Command /cg cannot be alias for itself
08.02 21:14:17 [Server] ERROR Encountered an unexpected exception

**Comment by oloflarsson** [comment]
Update to the latest version of MassiveCore and CreativeGates.
