### ISSUE TITLE
Add API Events 

### ISSUE THREAD

**Issue by MarkehMe** [MassiveCraft/CreativeGates#83]
Hi,

I'm trying to integrated CreativeGates and I've just had to do it a very hackish way. 

I'd like to suggest adding these events:
* CreativeGatesEventUseGate
* CreativeGatesEventCreateGate
* CreativeGatesEventDestroyGate

All being cancellable and such. :) Thank you!

**Comment by ulumulu1510** [comment]
If this is still your wish, I am sure today you are able to implement these events yourself ^^. It wouldn't be too much work I believe.

**Comment by MarkehMe** [comment]
I don't see why not :p

**Comment by MarkehMe** [comment]
Closing as @oloflarsson is implementing this in the rewrite version
